# Generated by Django 4.1 on 2022-08-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ytube', '0004_author_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Ytube.author', verbose_name='Автор'),
        ),
    ]
