# Generated by Django 4.1 on 2022-09-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_comment_options_comment_level_comment_lft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
