# Generated by Django 4.1 on 2022-09-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_rename_user_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
