# Generated by Django 4.1 on 2022-08-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
